
# Project ID is the first parameter
project_id = "your-project-id-placeholder"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
shadow_port = 54320

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
port = 54327

[auth]
enabled = true
port = 54328

[analytics]
enabled = true
port = 54329

[realtime]
enabled = true

[functions.send-contact-email]
verify_jwt = false
